/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './arms.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './arms.component';
const styles_ArmsComponent:any[] = [i0.styles];
export const RenderType_ArmsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ArmsComponent,data:{}});
export function View_ArmsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  arms works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_ArmsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-arms',([] as any[]),
      (null as any),(null as any),(null as any),View_ArmsComponent_0,RenderType_ArmsComponent)),
      i1.ɵdid(114688,(null as any),0,i2.ArmsComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ArmsComponentNgFactory:i1.ComponentFactory<i2.ArmsComponent> = i1.ɵccf('app-arms',
    i2.ArmsComponent,View_ArmsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvd29ya291dHMvYXJtcy9hcm1zLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9BZG1pbmlzdHJhdG9yL0Rlc2t0b3AvV29ya3NwYWNlL2FuZ3VsYXItd2Vic2l0ZS9hc3NldHMvYXBwL3dvcmtvdXRzL2FybXMvYXJtcy5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9BZG1pbmlzdHJhdG9yL0Rlc2t0b3AvV29ya3NwYWNlL2FuZ3VsYXItd2Vic2l0ZS9hc3NldHMvYXBwL3dvcmtvdXRzL2FybXMvYXJtcy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvd29ya291dHMvYXJtcy9hcm1zLmNvbXBvbmVudC50cy5Bcm1zQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIGFybXMgd29ya3MhXG48L3A+XG4iLCI8YXBwLWFybXM+PC9hcHAtYXJtcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLHVDQUVDO01BQUE7OztvQkNGSjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
