/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './landing-page.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from './landing-page.component';
const styles_LandingPageComponent:any[] = [i0.styles];
export const RenderType_LandingPageComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_LandingPageComponent,data:{}});
export function View_LandingPageComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),14,'div',[['class',
      'jumbotron']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'a',[['class','visible-xs'],['data-toggle','offcanvas'],['href','#']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),0,'i',[['class','fa fa-lg fa-reorder']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['The Block'])),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['Website for workout stuff.'])),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'button',[['class',
          'btn btn-primary'],['routerLink','/sign-up']],(null as any),[[(null as any),
          'click']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,12).onClick()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(16384,(null as any),0,i2.RouterLink,
          [i2.Router,i2.ActivatedRoute,[8,(null as any)],i1.Renderer2,i1.ElementRef],
          {routerLink:[0,'routerLink']},(null as any)),(_l()(),i1.ɵted((null as any),
          ['Sign Up!'])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    const currVal_0:any = '/sign-up';
    _ck(_v,12,0,currVal_0);
  },(null as any));
}
export function View_LandingPageComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-landing-page',
      ([] as any[]),(null as any),(null as any),(null as any),View_LandingPageComponent_0,
      RenderType_LandingPageComponent)),i1.ɵdid(114688,(null as any),0,i3.LandingPageComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const LandingPageComponentNgFactory:i1.ComponentFactory<i3.LandingPageComponent> = i1.ɵccf('app-landing-page',
    i3.LandingPageComponent,View_LandingPageComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvbGFuZGluZy1wYWdlL2xhbmRpbmctcGFnZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvQWRtaW5pc3RyYXRvci9EZXNrdG9wL1dvcmtzcGFjZS9hbmd1bGFyLXdlYnNpdGUvYXNzZXRzL2FwcC9sYW5kaW5nLXBhZ2UvbGFuZGluZy1wYWdlLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvbGFuZGluZy1wYWdlL2xhbmRpbmctcGFnZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvbGFuZGluZy1wYWdlL2xhbmRpbmctcGFnZS5jb21wb25lbnQudHMuTGFuZGluZ1BhZ2VDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwianVtYm90cm9uXCI+XG4gIDxhIGhyZWY9XCIjXCIgY2xhc3M9XCJ2aXNpYmxlLXhzXCIgZGF0YS10b2dnbGU9XCJvZmZjYW52YXNcIj48aSBjbGFzcz1cImZhIGZhLWxnIGZhLXJlb3JkZXJcIj48L2k+PC9hPlxuICA8aDE+VGhlIEJsb2NrPC9oMT5cbiAgPHA+V2Vic2l0ZSBmb3Igd29ya291dCBzdHVmZi48L3A+XG4gIDxidXR0b24gY2xhc3M9XCJidG4gYnRuLXByaW1hcnlcIiByb3V0ZXJMaW5rPVwiL3NpZ24tdXBcIj5TaWduIFVwITwvYnV0dG9uPlxuPC9kaXY+XG4iLCI8YXBwLWxhbmRpbmctcGFnZT48L2FwcC1sYW5kaW5nLXBhZ2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXVCLHlDQUNyQjtVQUFBO1VBQUE7TUFBdUQ7VUFBQTtNQUF1Qyx5Q0FDOUY7VUFBQTtVQUFBLGdCQUFJLDhDQUFjO1VBQUEsV0FDbEI7VUFBQTtNQUFHLCtEQUE4QjtVQUFBLFdBQ2pDO1VBQUE7VUFBQTtRQUFBO1FBQUE7VUFBQTtVQUFBO1FBQUE7UUFBQTtNQUFBLHVDQUFBO1VBQUE7VUFBQSw2Q0FBc0Q7VUFBQSxlQUFpQix1Q0FDbkU7VUFBQTtJQUQ0QjtJQUFoQyxZQUFnQyxTQUFoQzs7OztvQkNKRjtNQUFBO3FDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
