/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './shoulders.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './shoulders.component';
const styles_ShouldersComponent:any[] = [i0.styles];
export const RenderType_ShouldersComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ShouldersComponent,data:{}});
export function View_ShouldersComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  shoulders works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_ShouldersComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-shoulders',
      ([] as any[]),(null as any),(null as any),(null as any),View_ShouldersComponent_0,
      RenderType_ShouldersComponent)),i1.ɵdid(114688,(null as any),0,i2.ShouldersComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ShouldersComponentNgFactory:i1.ComponentFactory<i2.ShouldersComponent> = i1.ɵccf('app-shoulders',
    i2.ShouldersComponent,View_ShouldersComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvd29ya291dHMvc2hvdWxkZXJzL3Nob3VsZGVycy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvQWRtaW5pc3RyYXRvci9EZXNrdG9wL1dvcmtzcGFjZS9hbmd1bGFyLXdlYnNpdGUvYXNzZXRzL2FwcC93b3Jrb3V0cy9zaG91bGRlcnMvc2hvdWxkZXJzLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvd29ya291dHMvc2hvdWxkZXJzL3Nob3VsZGVycy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvd29ya291dHMvc2hvdWxkZXJzL3Nob3VsZGVycy5jb21wb25lbnQudHMuU2hvdWxkZXJzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIHNob3VsZGVycyB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtc2hvdWxkZXJzPjwvYXBwLXNob3VsZGVycz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLDRDQUVDO01BQUE7OztvQkNGSjtNQUFBO21DQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
