/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './chest.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './chest.component';
const styles_ChestComponent:any[] = [i0.styles];
export const RenderType_ChestComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ChestComponent,data:{}});
export function View_ChestComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  chest works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_ChestComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-chest',([] as any[]),
      (null as any),(null as any),(null as any),View_ChestComponent_0,RenderType_ChestComponent)),
      i1.ɵdid(114688,(null as any),0,i2.ChestComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ChestComponentNgFactory:i1.ComponentFactory<i2.ChestComponent> = i1.ɵccf('app-chest',
    i2.ChestComponent,View_ChestComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvd29ya291dHMvY2hlc3QvY2hlc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvd29ya291dHMvY2hlc3QvY2hlc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvQWRtaW5pc3RyYXRvci9EZXNrdG9wL1dvcmtzcGFjZS9hbmd1bGFyLXdlYnNpdGUvYXNzZXRzL2FwcC93b3Jrb3V0cy9jaGVzdC9jaGVzdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvd29ya291dHMvY2hlc3QvY2hlc3QuY29tcG9uZW50LnRzLkNoZXN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIGNoZXN0IHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1jaGVzdD48L2FwcC1jaGVzdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLHdDQUVDO01BQUE7OztvQkNGSjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
