/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app-routing.module';
import * as i2 from './landing-page/landing-page.component.ngfactory';
import * as i3 from './articles/articles.component.ngfactory';
import * as i4 from './signup/signup.component.ngfactory';
import * as i5 from './tools/tools.component.ngfactory';
import * as i6 from './recipes/recipes.component.ngfactory';
import * as i7 from './workouts/workouts.component.ngfactory';
import * as i8 from './workouts/arms/arms.component.ngfactory';
import * as i9 from './workouts/back/back.component.ngfactory';
import * as i10 from './workouts/chest/chest.component.ngfactory';
import * as i11 from './workouts/shoulders/shoulders.component.ngfactory';
import * as i12 from './workouts/legs/legs.component.ngfactory';
import * as i13 from '@angular/router';
import * as i14 from '@angular/common';
import * as i15 from './landing-page/landing-page.component';
import * as i16 from './articles/articles.component';
import * as i17 from './signup/signup.component';
import * as i18 from './tools/tools.component';
import * as i19 from './recipes/recipes.component';
import * as i20 from './workouts/workouts.component';
import * as i21 from './workouts/arms/arms.component';
import * as i22 from './workouts/back/back.component';
import * as i23 from './workouts/chest/chest.component';
import * as i24 from './workouts/shoulders/shoulders.component';
import * as i25 from './workouts/legs/legs.component';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.LandingPageComponentNgFactory,i3.ArticlesComponentNgFactory,i4.SignupComponentNgFactory,
              i5.ToolsComponentNgFactory,i6.RecipesComponentNgFactory,i7.WorkoutsComponentNgFactory,
              i8.ArmsComponentNgFactory,i9.BackComponentNgFactory,i10.ChestComponentNgFactory,
              i11.ShouldersComponentNgFactory,i12.LegsComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i13.ActivatedRoute,i13.ɵf,[i13.Router]),
          i0.ɵmpd(4608,i13.NoPreloading,i13.NoPreloading,([] as any[])),i0.ɵmpd(6144,
              i13.PreloadingStrategy,(null as any),[i13.NoPreloading]),i0.ɵmpd(135680,
              i13.RouterPreloader,i13.RouterPreloader,[i13.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i13.PreloadingStrategy]),i0.ɵmpd(4608,i13.PreloadAllModules,
              i13.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i0.NgProbeToken,() => {
            return [i13.ɵb()];
          },([] as any[])),i0.ɵmpd(4608,i13.ɵg,i13.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i13.ɵh(p0_0)];
              },[i13.ɵg]),i0.ɵmpd(5120,i13.ROUTER_INITIALIZER,i13.ɵi,[i13.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i13.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i13.ɵa,i13.ɵd,[[3,i13.Router]]),
          i0.ɵmpd(512,i13.UrlSerializer,i13.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i13.ChildrenOutletContexts,i13.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i13.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i14.LocationStrategy,
              i13.ɵc,[i14.PlatformLocation,[2,i14.APP_BASE_HREF],i13.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i14.Location,i14.Location,[i14.LocationStrategy]),i0.ɵmpd(512,
              i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i13.ROUTES,() => {
            return [[{path:'',component:i15.LandingPageComponent},{path:'articles',
                component:i16.ArticlesComponent},{path:'sign-up',component:i17.SignupComponent},
                {path:'tools',component:i18.ToolsComponent},{path:'recipes',component:i19.RecipesComponent},
                {path:'workouts',component:i20.WorkoutsComponent,children:[{path:'',
                    redirectTo:'arms',pathMatch:'full'},{path:'arms',component:i21.ArmsComponent},
                    {path:'back',component:i22.BackComponent},{path:'chest',component:i23.ChestComponent},
                    {path:'shoulders',component:i24.ShouldersComponent},{path:'legs',
                        component:i25.LegsComponent}]}]];
          },([] as any[])),i0.ɵmpd(1024,i13.Router,i13.ɵe,[i0.ApplicationRef,i13.UrlSerializer,
              i13.ChildrenOutletContexts,i14.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i13.ROUTES,i13.ROUTER_CONFIGURATION,[2,i13.UrlHandlingStrategy],
              [2,i13.RouteReuseStrategy]]),i0.ɵmpd(512,i13.RouterModule,i13.RouterModule,
              [[2,i13.ɵa],[2,i13.Router]]),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvYXBwLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvYXBwLXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
