/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './landing-page/landing-page.component.ngfactory';
import * as i4 from './articles/articles.component.ngfactory';
import * as i5 from './signup/signup.component.ngfactory';
import * as i6 from './tools/tools.component.ngfactory';
import * as i7 from './recipes/recipes.component.ngfactory';
import * as i8 from './workouts/workouts.component.ngfactory';
import * as i9 from './workouts/arms/arms.component.ngfactory';
import * as i10 from './workouts/back/back.component.ngfactory';
import * as i11 from './workouts/chest/chest.component.ngfactory';
import * as i12 from './workouts/shoulders/shoulders.component.ngfactory';
import * as i13 from './workouts/legs/legs.component.ngfactory';
import * as i14 from './app.component.ngfactory';
import * as i15 from '@angular/common';
import * as i16 from '@angular/platform-browser';
import * as i17 from '@angular/router';
import * as i18 from '@angular/forms';
import * as i19 from './articles/articles.service';
import * as i20 from './workouts/workouts.service';
import * as i21 from './landing-page/landing-page.component';
import * as i22 from './articles/articles.component';
import * as i23 from './signup/signup.component';
import * as i24 from './tools/tools.component';
import * as i25 from './recipes/recipes.component';
import * as i26 from './workouts/workouts.component';
import * as i27 from './workouts/arms/arms.component';
import * as i28 from './workouts/back/back.component';
import * as i29 from './workouts/chest/chest.component';
import * as i30 from './workouts/shoulders/shoulders.component';
import * as i31 from './workouts/legs/legs.component';
import * as i32 from './app-routing.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.LandingPageComponentNgFactory,i4.ArticlesComponentNgFactory,i5.SignupComponentNgFactory,
              i6.ToolsComponentNgFactory,i7.RecipesComponentNgFactory,i8.WorkoutsComponentNgFactory,
              i9.ArmsComponentNgFactory,i10.BackComponentNgFactory,i11.ChestComponentNgFactory,
              i12.ShouldersComponentNgFactory,i13.LegsComponentNgFactory,i14.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i15.NgLocalization,i15.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i16.DomSanitizer,i16.ɵe,[i15.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i16.DomSanitizer]),i0.ɵmpd(4608,
              i16.HAMMER_GESTURE_CONFIG,i16.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i16.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i16.ɵDomEventsPlugin(p0_0),new i16.ɵKeyEventsPlugin(p1_0),
                    new i16.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i15.DOCUMENT,i15.DOCUMENT,i15.DOCUMENT,i16.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i16.EventManager,i16.EventManager,[i16.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i16.ɵDomSharedStylesHost,i16.ɵDomSharedStylesHost,
              [i15.DOCUMENT]),i0.ɵmpd(4608,i16.ɵDomRendererFactory2,i16.ɵDomRendererFactory2,
              [i16.EventManager,i16.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,
              (null as any),[i16.ɵDomRendererFactory2]),i0.ɵmpd(6144,i16.ɵSharedStylesHost,
              (null as any),[i16.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,
              i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i16.Meta,i16.Meta,[i15.DOCUMENT]),
          i0.ɵmpd(4608,i16.Title,i16.Title,[i15.DOCUMENT]),i0.ɵmpd(5120,i17.ActivatedRoute,
              i17.ɵf,[i17.Router]),i0.ɵmpd(4608,i17.NoPreloading,i17.NoPreloading,
              ([] as any[])),i0.ɵmpd(6144,i17.PreloadingStrategy,(null as any),[i17.NoPreloading]),
          i0.ɵmpd(135680,i17.RouterPreloader,i17.RouterPreloader,[i17.Router,i0.NgModuleFactoryLoader,
              i0.Compiler,i0.Injector,i17.PreloadingStrategy]),i0.ɵmpd(4608,i17.PreloadAllModules,
              i17.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i17.ROUTER_INITIALIZER,
              i17.ɵi,[i17.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i17.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i18.ɵi,i18.ɵi,([] as any[])),i0.ɵmpd(4608,
              i18.FormBuilder,i18.FormBuilder,([] as any[])),i0.ɵmpd(4608,i19.ArticlesService,
              i19.ArticlesService,([] as any[])),i0.ɵmpd(4608,i20.WorkoutsService,
              i20.WorkoutsService,([] as any[])),i0.ɵmpd(512,i15.CommonModule,i15.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i16.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i17.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i17.ɵg,i17.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i16.ɵc(p0_0,p0_1),i17.ɵh(p1_0)];
              },[[2,i16.NgProbeToken],[2,i0.NgProbeToken],i17.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i16.BrowserModule,i16.BrowserModule,[[3,i16.BrowserModule]]),
          i0.ɵmpd(1024,i17.ɵa,i17.ɵd,[[3,i17.Router]]),i0.ɵmpd(512,i17.UrlSerializer,
              i17.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i17.ChildrenOutletContexts,
              i17.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i17.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i15.LocationStrategy,i17.ɵc,[i15.PlatformLocation,
              [2,i15.APP_BASE_HREF],i17.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i15.Location,
              i15.Location,[i15.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i17.ROUTES,
              () => {
                return [[{path:'',component:i21.LandingPageComponent},{path:'articles',
                    component:i22.ArticlesComponent},{path:'sign-up',component:i23.SignupComponent},
                    {path:'tools',component:i24.ToolsComponent},{path:'recipes',component:i25.RecipesComponent},
                    {path:'workouts',component:i26.WorkoutsComponent,children:[{path:'',
                        redirectTo:'arms',pathMatch:'full'},{path:'arms',component:i27.ArmsComponent},
                        {path:'back',component:i28.BackComponent},{path:'chest',component:i29.ChestComponent},
                        {path:'shoulders',component:i30.ShouldersComponent},{path:'legs',
                            component:i31.LegsComponent}]}]];
              },([] as any[])),i0.ɵmpd(1024,i17.Router,i17.ɵe,[i0.ApplicationRef,i17.UrlSerializer,
              i17.ChildrenOutletContexts,i15.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i17.ROUTES,i17.ROUTER_CONFIGURATION,[2,i17.UrlHandlingStrategy],
              [2,i17.RouteReuseStrategy]]),i0.ɵmpd(512,i17.RouterModule,i17.RouterModule,
              [[2,i17.ɵa],[2,i17.Router]]),i0.ɵmpd(512,i32.AppRoutingModule,i32.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i18.ɵba,i18.ɵba,([] as any[])),i0.ɵmpd(512,
              i18.FormsModule,i18.FormsModule,([] as any[])),i0.ɵmpd(512,i18.ReactiveFormsModule,
              i18.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FkbWluaXN0cmF0b3IvRGVza3RvcC9Xb3Jrc3BhY2UvYW5ndWxhci13ZWJzaXRlL2Fzc2V0cy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9BZG1pbmlzdHJhdG9yL0Rlc2t0b3AvV29ya3NwYWNlL2FuZ3VsYXItd2Vic2l0ZS9hc3NldHMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
